# Generated by Django 5.1.3 on 2025-08-05 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.CharField(help_text='Display name of person who created this invite', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Maximum number of times this link can be used')),
                ('current_uses', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Purpose of this invite link')),
                ('target_audience', models.CharField(blank=True, help_text='Who is this invite for?', max_length=200)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, help_text='User who created this invite', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_manage_all_invites', 'Can manage all invitation links'), ('can_view_invite_stats', 'Can view invitation statistics')],
            },
        ),
        migrations.CreateModel(
            name='RegisteredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('activity', models.TextField()),
                ('organisation', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('invite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.invitelink')),
            ],
            options={
                'ordering': ['-registered_at'],
                'permissions': [('can_verify_registrations', 'Can verify registrations'), ('can_export_registrations', 'Can export registration data')],
            },
        ),
        migrations.CreateModel(
            name='InviteUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('successful_registration', models.BooleanField(default=False)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='main.invitelink')),
                ('registered_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.registeredperson')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('can_create_invites', models.BooleanField(default=True, help_text='Can this staff member create invitation links?')),
                ('max_invites_per_day', models.IntegerField(default=10, help_text='Maximum invites this staff can create per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
