# Generated by Django 5.2.5 on 2025-08-22 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelink',
            options={},
        ),
        migrations.RemoveField(
            model_name='invitelink',
            name='current_uses',
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='max_uses',
            field=models.IntegerField(default=1, help_text='How many times each user can register with this link'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='UserInviteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Email, phone, or IP address', max_length=255)),
                ('identifier_type', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('ip', 'IP Address')], max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='main.invitelink')),
                ('registered_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registeredperson')),
            ],
            options={
                'indexes': [models.Index(fields=['invite', 'identifier'], name='main_userin_invite__ba0e25_idx')],
                'unique_together': {('invite', 'registered_person')},
            },
        ),
    ]
