# Generated by Django 5.2.5 on 2025-08-25 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_archived_to_invitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='current_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredperson',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='main.invitelink'),
        ),
    ]
