# Generated by Django 5.2.5 on 2025-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_invitelink_current_uses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='invitelink',
            name='title',
            field=models.CharField(default='Staff workshop', max_length=200),
        ),
    ]
