# Generated by Django 5.2.5 on 2025-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_invitelink_target_audience_invitelink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='max_uses',
            field=models.IntegerField(default=1, help_text='How many times the same user (identifier) can register with this link'),
        ),
        migrations.AlterUniqueTogether(
            name='userinviteusage',
            unique_together={('invite', 'identifier')},
        ),
    ]
