# Generated by Django 5.2.5 on 2025-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_invitelink_max_uses_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registeredperson',
            constraint=models.UniqueConstraint(fields=('invite', 'email'), name='unique_registration_per_invite_email'),
        ),
    ]
